name: Run Telegram Bot

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 30 # 30 menit

    steps:
      # =======================
      # 1️⃣ Checkout repository
      # =======================
      - name: Checkout repository
        uses: actions/checkout@v4

      # =======================
      # 2️⃣ Setup Python
      # =======================
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # =======================
      # 3️⃣ Setup .NET 8
      # =======================
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # ✅ Tambahan: install native dependencies (libgdiplus & unzip)
      - name: Install native dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgdiplus libgtk-3-0 unzip

      # =======================
      # 4️⃣ Extract bot files
      # =======================
      - name: Extract bot files
        run: unzip Bot.zip -d Bot

      - name: Extract AssetStudio
        run: |
          unzip AssetStudio.zip -d AssetStudio
          ls -R AssetStudio

      # 🔍 Debug AssetStudio CLI
      - name: Debug AssetStudio CLI
        run: |
          echo "=== DOTNET INFO ==="
          dotnet --info
          echo "=== CLI HELP ==="
          dotnet AssetStudio/AssetStudio.CLI.dll --help || true
          echo "=== END OF HELP ==="
        
      # =======================
      # 5️⃣ Install dependencies
      # =======================
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Bot/requirements.txt

      # =======================
      # 6️⃣ Jalankan bot Telegram
      # =======================
      - name: Run Telegram Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: |
          echo "🤖 Starting Telegram bot..."
          cd Bot
          python bot.py

      # =======================
      # 7️⃣ Bersihkan cache sementara
      # =======================
      - name: Clean up temporary files
        if: always()
        run: |
          echo "🧹 Cleaning up..."
          rm -rf __pycache__ Bot/__pycache__ AssetStudio/__pycache__
