name: Menjalankan Bot LeakerID👨‍💻

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 120  # 2 Jam
    
    steps:
      # =======================
      # 1️⃣ Setup Python
      # =======================
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # =======================
      # 2️⃣ Checkout Repository
      # =======================
      - name: Checkout Repository
        uses: actions/checkout@v4

      # =======================
      # 3️⃣ Mengestrak File Bot.zip
      # =======================
      - name: Ekstrak File Bot.zip📁
        run: |
          unzip Bot.zip -d Bot
          ls -R Bot

      # =======================
      # 4️⃣ Install Dependencies
      # =======================
      - name: Menginstal Python Dependencies🔗
        run: |
          python -m pip install --upgrade pip
          pip install -r Bot/requirements.txt

      # =======================
      # 5️⃣ Jalankan bot Telegram
      # =======================
      - name: Menjalankan Bot Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          SHUTDOWN_TIME: ${{ secrets.SHUTDOWN_TIME || '300' }}
        run: |
          echo "🤖 Memulai Bot Telegram..."
          cd Bot
          python bot.py

      # =======================
      # 6️⃣ Bersihkan file sementara
      # =======================
      - name: Membersihkan File
        if: always()
        run: |
          echo "🧹 Membersihkan..."
          rm -rf pycache
          rm -rf *.zip
          rm -rf tmp/
          rm -rf assets/
